desktop <number_small>: user.desktop(number_small)
desktop next: user.desktop_next()
desktop last: user.desktop_last()
desktop show: user.desktop_show()
window move desktop <number>: user.window_move_desktop(number)
window move desktop left: user.window_move_desktop_left()
window move _right: user.window_move_desktop_right()
